src/components/common/NavigationBar/NavigationBar.css
src/components/common/NavigationBar/NavigationBar.tsx

네비게이션 바 추가 - 로고, 검색창, 마이페이지 버튼, 로그인&로그아웃 버튼
(링크는 작성하지 않음)
- 스토리북으로 테스트 완료 -> 디자인은 추가로 수정 예정
Related to #1

feat: navigationBar

---

next.config.ts
package-lock.json
package.json
src/app/webtoon-detail/[id]/ClientPage.tsx
src/app/webtoon-detail/[id]/page.tsx
src/components/common/NavigationBar/NavigationBar.tsx
src/components/ui/badge.tsx
src/components/ui/card.tsx
src/lib/api/user/user.ts
src/lib/api/webtoon/webtoon.ts

shadcn을 사용해 ui를 만들어봤는데 값은 제대로 전달되고 화면에 제대로 나오는 상태이고 ui 부분은 제가 디자인에 감각이 없어서 간격만 맞춰서 해놨는데 혹시 실행해보시고 마음에 안드시면 수정하셔도 무방합니다! 
폴더를  webtoon-detail/[id] 로 바꾸어 localhost:3000/webtoon-detail/{id} 값이 입력되면 page가 나오게 수정하였습니다
close #13

Feat:WebtoonDetail 페이지 구현

---

src/components/webtoon/webtoonItem.tsx

검색결과로 나온 웹툰 박스를 누르면
webty의 상세웹툰 페이지로 이동하도록 만들었습니다.

feat 상세웹툰페이지로 이동 추가

---

package-lock.json
package.json
src/app/mypage/page.tsx
src/components/buisness/mypage/EditNickname.tsx
src/components/buisness/mypage/ProfileSection.tsx
src/components/ui/input.tsx
src/components/ui/separator.tsx
src/lib/api/user/userProfile.ts

refactor : 마이페이지 모듈화

---

src/app/mypage/page.tsx
src/components/common/NavigationBar/NavigationBar.tsx

네비게이션바가 적용되는 곳을 수정했습니다.
/123 같은 패스경로같은 경우를 처리하려면 이렇게 수정해야 하는 것 같습니다.
마이페이지의 경우 div으로 네비게이션까지 감싸서 다르게보이던걸 수정했습니다.

chore: navigationbar 수정

---

src/components/buisness/webtoon/WebtoonItem.tsx
src/components/buisness/webtoon/WebtoonList.tsx

웹툰리스트 가로정렬 기능을 추가했습니다.
WebtoonList를 호출해서 사용하실 때, 
<WebtoonList isHorizontal={true} /> ..
isHorizontal={true} 옵션을 주면 가로로 정렬이 가능하고, 현재 최대 3개까지 들어가게 해놨습니다.

feature 웹툰리스트 가로정렬기능 추가 (디폴트 = 세로정렬)

---

src/app/callback/page.tsx
src/lib/api/user/user.ts

로그인 (원래 위치 저장) -> callback page -> 원래 있던 위치 이동
[관련 velog 정리글](https://velog.io/@dia218/Client-Login-Callback)
close #55

fix: Login Callback

---

src/components/buisness/mypage/UserDrawerTaps.tsx
src/components/buisness/search/webtoonPage.tsx

관심 웹툰 1줄에 3개씩 나오도록 수정했습니다
~~이후 새 이슈에서 `WebtoonList` 자체에 페이지네이션 버튼을 내장하도록 수정할 것 같습니다~~
(`WebtoonList`에 넣으면 재사용에 제한이 생길까봐 우선 조금 더 고민해보고 다른 브랜치에서 수정하도록 하겠습니다)
close #58

fix: FavoriteList(UserDrawerTaps) Col 1 -> 3

---

package-lock.json
package.json
src/app/review/page.tsx
src/components/buisness/mypage/UserDrawerTaps.tsx
src/components/buisness/review/EditReview.tsx
src/components/common/NavigationBar/hiddenElements.ts
src/components/common/ReviewWriteModal/ReviewWriteModal.tsx
src/components/common/reviewDialog/InputAlertDialog.tsx
src/components/common/reviewDialog/ReviewDialog.tsx
src/components/common/reviewForm/ReviewForm.tsx
src/components/ui/label.tsx
src/components/ui/switch.tsx
src/components/ui/textarea.tsx
src/lib/api/review/review.ts
src/lib/types/review/ReviewRequestDto.ts

리뷰 작성 폼을 만들어 리뷰 작성, 수정시에 사용 할 수 있도록 만들었습니다
리뷰 작성 시 제목이 빠져있거나 내용이 빠져있으면 alert-dialog가 뜨도록 하였습니다 .
리뷰 작성 버튼클릭 시 작성성공/실패 메세지와 함께 alert-dialog가 뜨도록 하였습니다.
파일 선택시 몇개의 파일이 선택되었는지 보여주고 선택된 파일옆 X 버튼을 누르면 선택된 파일이 삭제 되도록 하였습니다.
테스트 결과 백엔드 와도 잘 통신이 되는것을 확인하였고 DB에도 저장되는것을 확인하였습니다.
close #48

Feat:리뷰 작성 폼, 리뷰 작성 페이지

---

src/app/feed/page.tsx
src/app/page.tsx

메인페이지 접속 시 피드페이지로 이동하도록 설정했습니다
close #54

fix: MainPage -> FeedPage

---

src/components/common/ReviewWriteModal/ReviewWriteModal.tsx

fix ReviewWriteModal.tsx 문제 해결

---

src/app/review-detail/[id]/page.tsx
src/components/buisness/review/ReviewDetail.tsx
src/components/common/UpdateDeleteButtons/UpdateDeleteButtons.tsx
src/lib/api/review/review.ts

수정같은 경우엔 폼이 따로 만들어지던가 해야 구현 가능할것 같습니다.

feat: 수정삭제버튼 구현 (수정 내부 미구현)

---

src/components/buisness/review/ReviewDetail.tsx
src/components/common/RecommendButton/RecommendButton.tsx

추천버튼 비추천버튼 만들었습니다.
인자로 3개를 받는데
isInitialActive?: boolean;         =>          사용하는 page.tsx에서 현재 로그인한 유저면 추천/비추천 상태를 받아와 넘겨줘야 함
isLoggedIn: boolean;          =>          사용하는 page.tsx에서 useAuth로 로그인 여부 넘겨줘야 함
onClick: () => void;         =>          사용할 함수
이렇게 다 분리해서 재사용할 수 있게 만들긴 했는데, 막상 크기때문에 재사용이 될지 안될지는 모르겠습니다.

feat RecommendButton 2개

---

src/app/review-detail/[id]/page.tsx
src/components/buisness/review/ReviewDetail.tsx
src/lib/api/review/recommend.ts
src/lib/api/security/useAuth.ts

일단 recommend.ts에 추천관련 필요한기능 다 넣었습니다.
로그인한 사용자면 추천/비추천 기능 사용 가능합니다.
로그인한 유저면 추천여부를 받아와 바로 반영합니다.
기존 코드에서 작성자가 아니여도 수정삭제버튼이 다보이는데 그것도 일단은 수정해두었습니다.
UseAuth쪽도 건드리게 되었는데, 초기값이 null 이여야 UseEffect에서 초기값 false를 바로 받아오는 문제를
해결할 수 있다고 하여 건드리게 되었습니다.

feat: 추천 비추천 상태조회 및 등록 삭제 요청기능 추가

---

src/components/buisness/review/ReviewDetail.tsx
src/components/common/RecommendButton/ReviewRecommendBox.tsx

디자인은 나중에 한번에 몰아서 하고
일단 Box부터 만들어두려고 합니다.

feat: ReviewRecommnedationBox

---

src/components/buisness/review/ReviewContentBox.tsx
src/components/buisness/review/ReviewDetail.tsx

feat: ReviewContentBox

---

src/app/review-detail/[id]/page.tsx
src/components/buisness/review/ReviewDetail.tsx
src/lib/api/security/useAuth.ts

chore: userId 기능 추가

---

src/components/buisness/review/ReviewDetail.tsx
src/components/buisness/review/ReviewRecommendBox.tsx

chore: ReviewRecommendBox

---

src/components/common/CommentList/CommentItem.stories.tsx
src/components/common/CommentList/CommentItem.tsx
src/components/common/CommentList/NestedCommentItem.tsx
src/components/common/CommentList/RootCommentItem.tsx

인자:
CommentList 로부터 CommentResponseDto 를 받습니다
내부 컴포넌트:
- NestedCommentItem: childComments를 제외한 CommentResponseDto 데이터를 넘겨줍니다
- RootCommentItem: CommentResponseDto.childComments (CommentResponseDto) 를 넘겨줍니다
디자인은 나중에 수정이 필요합니다
우선, 데이터만 넘겨줍니다

feat: Implement CommentItem

---

src/components/buisness/review/ReviewDetail.tsx
src/components/buisness/review/ReviewRecommendBox.tsx
src/components/common/RecommendButton/RecommendButton.tsx

추천버튼 누르면 서버에선 상태가 바뀌어도 현재 보이는 화면은 바뀌지 않았는데
새로고침을 하지 않아도 추천카운트가 올라가고 내려가게 보이도록 바꿨습니다.

chore: 추천 ui/ux 경험 향상

---

src/app/webtoon-detail/[id]/page.tsx
src/components/buisness/webtoonDetail/WebtoonDrawerTaps.tsx
src/components/common/ResponsiveReviewBox/ResponsiveReviewBox.tsx
src/lib/api/review/review.ts

기존에 만들어둔 2개짜리 써서 만들었습니다.
백엔드 병합되야 사용 가능합니다.

feat: webtoon-detail 게시글보기 추가

---

src/app/search/page.tsx
src/components/buisness/review/ReviewDetail.tsx
src/components/buisness/review/UpdateReview.tsx
src/components/common/LargeReviewList/LargeReviewItem.tsx
src/components/common/ReviewWebtoonBox/ReviewWebtoonBox.tsx
src/components/common/SmallReviewList/SmallReviewItem.tsx
src/components/common/WideReviewList/WideReviewItem.tsx
src/lib/api/review/review.ts
src/lib/types/review/ReviewDetailResponseDto.ts
src/lib/types/review/ReviewItemResponseDto.ts

ReviewDetailResponseDto와 ReviewItemResponseDto에서 웹툰에 해당하는 부분을 WebtoonSummaryDto로 처리하였습니다
close #122

refactor: WebtoonSummaryDto 추가

---

src/app/review-detail/[id]/page.tsx
src/components/common/CommentList/CommentArea.tsx
src/components/common/CommentList/CommentItem.tsx
src/components/common/CommentList/CommentList.tsx
src/components/common/CommentList/MentionSuggestions.tsx
src/components/common/CommentList/NestedCommentItem.tsx
src/components/ui/comment-avatar.tsx
src/components/ui/comment-container.tsx
src/components/ui/comment-content.tsx
src/components/ui/comment-header.tsx
src/lib/api/reviewComment/reviewComment.ts
src/lib/types/reviewComment/CommentResponseDto.ts

Close #171
--- 
---
---
사용하는 위치:

feat: 댓글 대댓글 완성본

---

src/app/review-detail/[id]/page.tsx
src/components/buisness/reviewComment/ReviewCommentSection.tsx
src/components/common/CommentList/CommentItem.tsx
src/components/common/CommentList/CommentList.tsx
src/components/common/CommentList/MentionSuggestions.tsx
src/components/common/CommentList/NestedCommentItem.tsx
src/lib/api/reviewComment/reviewComment.ts

Close #173 
댓글작성 URL (/page) 을 빼다보니까 이미지와 같은 에러가 발생합니다.

fix: 댓글조회 로그인문제 보완, 멘션기능 보완
